[package]
name = "srml-slashing"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }
srml-support = { path = "../support", default-features = false }
primitives = { package = "sr-primitives", path = "../../core/sr-primitives", default-features = false }

[dev-dependencies]
balances = { package = "srml-balances", path = "../balances", default-features = false }
runtime_io = { package = "sr-io", path = "../../core/sr-io" }
substrate-primitives = { path = "../../core/primitives" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"rstd/std",
	"srml-support/std",
	"primitives/std",
	"system/std",
]
